# sns2f_framework/tools/code_executor.py

import sys
import io
import contextlib
import logging

log = logging.getLogger(__name__)

class CodeExecutor:
    """
    The 'Hands' of the swarm.
    Executes Python code generated by the Brain and captures the output.
    """

    @staticmethod
    def execute(code: str) -> str:
        """
        Runs a string of Python code in a restricted local scope.
        Captures stdout (print statements).
        """
        log.info("Executing generated code...")
        
        # Create a buffer to capture print() output
        output_buffer = io.StringIO()
        
        # Define a safe-ish scope
        # We explicitly ban 'input' so the agent doesn't hang the system waiting for user keys.
        safe_globals = {
            "math": __import__("math"), 
            "datetime": __import__("datetime"),
            "input": lambda *args: (_ for _ in ()).throw(RuntimeError("input() is forbidden. Hardcode your variables."))
        }
        
        try:
            with contextlib.redirect_stdout(output_buffer):
                # We exec the code string
                exec(code, safe_globals)
            
            result = output_buffer.getvalue().strip()
            if not result:
                result = "[Code ran successfully, but produced no output. Did you forget print()?]"
            
            return result

        except Exception as e:
            return f"Runtime Error: {e}"

# --- Self-Test ---
if __name__ == "__main__":
    test_code = """
import math
print(f"The square root of 16 is {math.sqrt(16)}")
"""
    print(CodeExecutor.execute(test_code))